### PR TITLE
Remove SSDT-XOSI. This can help get your I2C trackpad working properly

### PR DESCRIPTION
**Pull request by lzhoang2601**
Could you please double-check this issue and update the guide accordingly?

### CODE REVIEW

**Comment by ChefKissInc** [comment]
This is needed on some, not needed on others. The criteria isn't known. I've personally never heard of that causing issues, it's usually HPET. You've explained nothing about this PR

**Comment by ExtremeXT** [comment]
@lzhoang2601 Why would we remove it? It basically makes macOS be identified as a Windows version of your choosing, usually some Windows 10 version. On most laptops, this forces some devices like the I2C/GPIO controller, actual touchpad device, keyboard FN keys, etc to use the proper settings and device statuses. Most laptops need this for the above-mentioned features.

**Comment by lzhoang2601** [comment]
To enable GPI0 and I2Cx devices, the default TSOS value should be set to greater than 0x70. However, if SSDT-XOSI is used, the TSOS value will be lower than what is required.

[Imgur](https://i.imgur.com/W1Qr2v7.jpg)

[Imgur](https://i.imgur.com/02yy4eI.jpg)

[Imgur](https://i.imgur.com/XgZGVYk.png)

**Comment by ChefKissInc** [comment]
@lzhoang2601 That depends on the XOSI type. Also, this is specific to your device.

**Comment by ExtremeXT** [comment]
@lzhoang2601 TSOS will only be lower if you make it incorrectly. In most cases the automatic detection works perfectly.

**Pull request closed without merging**
